DealDoubleDash.Web/Controllers/AuctionController.cs
using DealDoubleDash.Entities;
using DealDoubleDash.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DealDoubleDash.Web.Controllers
{
    public class AuctionController : Controller
    {

        AuctionServices services = new AuctionServices();

        // GET: Auction
        public ActionResult Index()
        {
            var list = services.Listing();

            if (Request.IsAjaxRequest())
            {
                return PartialView(list);
            }
            else
            {
                return View(list);
            }

            
        }

        public ActionResult create()
        {
            return PartialView();
        }

        [HttpPost]
        public ActionResult create(tbl_Auction auction)
        {
            services.SaveAuction(auction);

            return RedirectToAction("Index");
        }

        public ActionResult Edit(int ID)
        {
            var auction = services.EditAuction(ID);

            return PartialView(auction);
        }

        [HttpPost]
        public ActionResult Edit(tbl_Auction auction)
        {
            services.SaveEdit(auction);

            return RedirectToAction("Index");
        }

        public ActionResult Delete(int ID)
        {
            var auction = services.EditAuction(ID);

            return View(auction);
        }

        [HttpPost]
        public ActionResult Delete(tbl_Auction auction)
        {
            services.DeleteAuction(auction);

            return  View(auction);
        }


        public ActionResult Details(int ID)
        {
            var auction = services.EditAuction(ID);

            return View(auction);
        }
    }
}

DealDoubleDash.Web/Controllers/HomeController.cs
using DealDoubleDash.DataBase;
using DealDoubleDash.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DealDoubleDash.Web.Controllers
{
    public class HomeController : Controller
    {
        DealDoubeDashContext context = new DealDoubeDashContext();

        AuctionServices services = new AuctionServices();

        public ActionResult Index()
        {
            var allauction = services.Listing();

            //var allauction = context.Auctions.ToList();

            return View(allauction);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

DealDoubleDash.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

DealDoubleDash.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

DealDoubleDash.Web/Views/Home/Index.cshtml
@model IEnumerable<DealDoubleDash.Entities.tbl_Auction>

<!-- Page Content -->
<div class="container">
    <div class="row">
        <!-- /.col-lg-3 -->
        <div class="col-lg-12">
            <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner" role="listbox">
                    <div class="carousel-item active">
                        <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Second slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Third slide">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
            <div class="row">
                @foreach (var item in Model)
                {
                    <div class="col-lg-4 col-md-6 mb-4">

                        <div class="card h-100">
                            <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
                            <div class="card-body">
                                <h4 class="card-title">
                                    <a href="@Url.Action("Details","Auction" , new { ID = item.id})">@item.Title</a>
                                </h4>
                                <h5>$ @item.ActualAmount</h5>
                                <p class="card-text">@item.Description</p>
                            </div>
                            <div class="card-footer">
                                <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                            </div>
                        </div>


                    </div>
                }


            </div>
            <!-- /.row -->
        </div>
        <!-- /.col-lg-9 -->
    </div>
    <!-- /.row -->
</div>
<!-- /.container -->